### PR TITLE
Keystone add params

### PR DESCRIPTION
**Pull request by shuwens**
Per our discussion in [PR#643](https://github.com/CCI-MOC/hil/pull/643), we need to enable the `params` in `HTTPClient` and `KeystoneHTTPClient`. Keystone underlying session allow us to pass parameters like this, see [doc](http://docs.openstack.org/developer/python-keystoneclient/using-sessions.html).  Is there something else I missed? @zenhack @knikolla 

Besides I want to test it with a keystone auth enabled environment, api call unit tests are missing.
- [x] The commits are consistent with our contribution guidelines
- [ ] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing (tests/unit, pep8)
- [ ] You've updated the documentation (if adding/changing api calls)

### CODE REVIEW

**Comment by henn** [comment]
Thanks, @shwsun , for these suggested changes.

It's very difficult for me to review this in its current form because it includes tons of commits that aren't part of the proposed changes.

Perhaps it'd be easier if you:
1. Created a new branch based on the latest master
2. Merged my changes in and then 
3. Made the adjustments to use the new HTTP Client.

What do you think?

**Comment by shuwens** [comment]
As a matter of fact, it is what I did. I think most of the commit will go away if you bring the `cli-get-params` up to date. Things that matter are basically in the last commit.

**Comment by zenhack** [comment]
I would just make a pr with this change directly at the cci-moc's master, without the dependency on @henn's patch at all. It's conceptually a prerequisite, not the other way around. I agree with @henn, this is really hard to look at.

**Comment by shuwens** [comment]
@zenhack make a pr at HIL sounds right. Those commits are there because I based from to-date's hil, i.e. it can solve the merging conflicts as well. Anyway, we can close this one.

**Comment by henn** [comment]
This has been merged. Closing.

**Pull request closed without merging**
