### PR TITLE
Network ACL

### PR DESCRIPTION
**Pull request by shuwens**
We should be able to kill Network ACL now! 

https://travis-ci.org/shwsun/haas/builds/152754364

### CODE REVIEW

**Comment by shuwens** [comment]
@henn I add the acl branch in `.travis.yml` and forget to remove it. Please take that out.

**Comment by henn** [comment]
Thank you Jethro!

I just tried to merge this code with my current henn/acl and got conflicts (see below).

I'm having a hard time figuring out which stuff is new stuff from you vs merges vs previous commits.

Would you mind cleaning up the history using `git rebase -i <base commit>` to squash unnecessary commits and add helpful messages? If it's too much work, and the changes to merge main aren't too tough, I could take a first pass at them once CCI-MOC/haas#554 is approved.

``` bash
$ git reset --hard henn/acl
$ git merge shwsun/acl
Auto-merging tests/unit/api/main.py
CONFLICT (content): Merge conflict in tests/unit/api/main.py
Auto-merging haas/cli.py
CONFLICT (content): Merge conflict in haas/cli.py
Auto-merging haas/api.py
CONFLICT (content): Merge conflict in haas/api.py
Auto-merging ci/testsuite.cfg.sqlite
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by shuwens** [comment]
I just pushed a commit. It should solve the conflict shown by auto-merge.

**Comment by henn** [comment]
@shwsun - there are a lot of changes in here.

I need to understand:
a) What consists of other people's commits
b) Which changes are due to merging
and c) Which are new code you've written.

To save you the effort, I can take care of merging things once we get the +1's for CCI-MOC/hil#554.

**Comment by henn** [comment]
Also, for b) and c), I would prefer if you could rebase your commits so that it's clear which changes fall into what categories.

Again, if this is too much work, I am happy to do the merging  when we get +1, so wouldn't suggest spending effort trying to keep this commit merge-error free.

**Pull request closed without merging**
